version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: new_technologies-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app_network
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:latest
        container_name: new_technologies-nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app_network
        depends_on:
            - app

    db:
        image: postgres:latest
        container_name: new_technologies-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: new_technologies
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5433:5432"
        networks:
            - app_network
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: new_technologies-redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    pgdata:
